import jsPDF from 'jspdf'
import QRCode from 'qrcode'

export interface ClaimSheetData {
  student: {
    id: string
    firstName: string
    lastName: string
    claimCode: string
  }
  org: {
    name: string
  }
  classes: Array<{
    name: string
  }>
  signupUrl: string
}

/**
 * Generate a PDF claim sheet for a student
 */
export async function generateClaimSheetPDF(data: ClaimSheetData): Promise<Buffer> {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20

  // Header
  pdf.setFontSize(20)
  pdf.setTextColor(17, 24, 39) // gray-900
  pdf.setFont(undefined, 'bold')
  pdf.text(data.org.name, margin, 30)

  pdf.setFontSize(12)
  pdf.setTextColor(107, 114, 128) // gray-500
  pdf.setFont(undefined, 'normal')
  pdf.text('Parent Portal Claim Sheet', margin, 40)

  // Student Information
  let y = 60
  pdf.setFontSize(14)
  pdf.setTextColor(17, 24, 39)
  pdf.setFont(undefined, 'bold')
  pdf.text('Student Information', margin, y)

  y += 15
  pdf.setFontSize(10)
  pdf.setFont(undefined, 'normal')
  pdf.setTextColor(55, 65, 81) // gray-700

  pdf.setFont(undefined, 'bold')
  pdf.text('Student Name:', margin, y)
  pdf.setFont(undefined, 'normal')
  pdf.text(`${data.student.firstName} ${data.student.lastName}`, margin + 50, y)
  y += 10

  if (data.classes.length > 0) {
    pdf.setFont(undefined, 'bold')
    pdf.text('Class:', margin, y)
    pdf.setFont(undefined, 'normal')
    pdf.text(data.classes.map(c => c.name).join(', '), margin + 50, y)
    y += 10
  }

  // Claim Code Section (Large and prominent)
  y += 10
  pdf.setFontSize(16)
  pdf.setFont(undefined, 'bold')
  pdf.setTextColor(17, 24, 39)
  pdf.text('Your Claim Code', margin, y)

  y += 15
  pdf.setFontSize(24)
  pdf.setTextColor(0, 0, 0)
  pdf.setFont('courier', 'bold')
  // Format code with dashes for readability
  const formattedCode = formatClaimCode(data.student.claimCode)
  pdf.text(formattedCode, margin, y)

  // QR Code
  try {
    const qrCodeDataUrl = await QRCode.toDataURL(data.signupUrl, {
      width: 100,
      margin: 1,
      color: {
        dark: '#000000',
        light: '#FFFFFF'
      }
    })

    // Add QR code image (positioned on the right side)
    const qrX = pageWidth - margin - 100
    const qrY = y - 20
    pdf.addImage(qrCodeDataUrl, 'PNG', qrX, qrY, 100, 100)
  } catch (error) {
    // If QR code generation fails, just continue without it
    console.error('Failed to generate QR code:', error)
  }

  // Instructions
  y += 30
  pdf.setFontSize(10)
  pdf.setFont(undefined, 'bold')
  pdf.setTextColor(17, 24, 39)
  pdf.text('How to Claim Your Account:', margin, y)

  y += 10
  pdf.setFont(undefined, 'normal')
  pdf.setTextColor(55, 65, 81)
  pdf.text('1. Scan the QR code above with your phone camera', margin, y, { maxWidth: pageWidth - (margin * 2) })
  y += 8
  pdf.text('2. Or visit the Parent Portal and enter your claim code', margin, y, { maxWidth: pageWidth - (margin * 2) })
  y += 8
  pdf.text('3. Create your account with your email and password', margin, y, { maxWidth: pageWidth - (margin * 2) })
  y += 8
  pdf.text('4. Verify your email to complete the setup', margin, y, { maxWidth: pageWidth - (margin * 2) })

  // Important Notes
  y += 15
  pdf.setFontSize(9)
  pdf.setFont(undefined, 'bold')
  pdf.setTextColor(239, 68, 68) // red-500
  pdf.text('Important:', margin, y)
  y += 8
  pdf.setFont(undefined, 'normal')
  pdf.setTextColor(55, 65, 81)
  pdf.text('• Keep this sheet safe and do not share your claim code', margin, y, { maxWidth: pageWidth - (margin * 2) })
  y += 8
  pdf.text('• Your claim code will expire in 90 days', margin, y, { maxWidth: pageWidth - (margin * 2) })
  y += 8
  pdf.text('• If you lose this sheet, contact the madrasah for a new code', margin, y, { maxWidth: pageWidth - (margin * 2) })

  // Footer
  const footerY = pdf.internal.pageSize.getHeight() - 20
  pdf.setFontSize(8)
  pdf.setTextColor(156, 163, 175) // gray-400
  pdf.setFont(undefined, 'normal')
  pdf.text('Generated by Madrasah OS', margin, footerY)
  pdf.text(`Student ID: ${data.student.id.slice(-8)}`, pageWidth - margin - 50, footerY, { align: 'right' })

  const pdfBuffer = Buffer.from(pdf.output('arraybuffer'))
  return pdfBuffer
}

/**
 * Format claim code for display (add dashes for readability)
 */
function formatClaimCode(code: string): string {
  if (!code) return ''
  // Format as: XXXX-XXXX-XX (10 chars) or similar
  if (code.length === 10) {
    return `${code.substring(0, 4)}-${code.substring(4, 8)}-${code.substring(8)}`
  }
  return code
}

/**
 * Generate multiple claim sheets and combine into one PDF
 */
export async function generateMultipleClaimSheetsPDF(sheets: ClaimSheetData[]): Promise<Buffer> {
  if (sheets.length === 0) {
    throw new Error('No sheets provided')
  }

  if (sheets.length === 1) {
    return generateClaimSheetPDF(sheets[0])
  }

  // Generate first sheet
  const firstPdf = await generateClaimSheetPDF(sheets[0])
  const pdf = new jsPDF()
  const pdfDoc = pdf as any

  // Add first page
  const firstPdfDoc = await (jsPDF as any).load(firstPdf)
  pdfDoc.addPage(firstPdfDoc.getPage(0))

  // Add remaining pages
  for (let i = 1; i < sheets.length; i++) {
    const sheetPdf = await generateClaimSheetPDF(sheets[i])
    const sheetDoc = await (jsPDF as any).load(sheetPdf)
    pdfDoc.addPage(sheetDoc.getPage(0))
  }

  const pdfBuffer = Buffer.from(pdf.output('arraybuffer'))
  return pdfBuffer
}

