import jsPDF from 'jspdf'
import { prisma } from './prisma'

export async function generatePaymentRecordPDF(paymentRecordId: string): Promise<Buffer> {
  const paymentRecord = await prisma.monthlyPaymentRecord.findUnique({
    where: { id: paymentRecordId },
    include: {
      student: {
        select: {
          firstName: true,
          lastName: true,
          dateOfBirth: true
        }
      },
      class: {
        select: {
          name: true
        }
      },
      org: {
        select: {
          name: true,
          address: true,
          phone: true,
          email: true
        }
      }
    }
  })

  if (!paymentRecord) {
    throw new Error('Payment record not found')
  }

  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20

  // Header
  pdf.setFontSize(20)
  pdf.setTextColor(17, 24, 39) // gray-900
  pdf.setFont(undefined, 'bold')
  pdf.text(paymentRecord.org.name, margin, 30)

  pdf.setFontSize(10)
  pdf.setTextColor(107, 114, 128) // gray-500
  pdf.setFont(undefined, 'normal')
  if (paymentRecord.org.address) {
    pdf.text(paymentRecord.org.address, margin, 40)
  }
  if (paymentRecord.org.phone) {
    pdf.text(`Phone: ${paymentRecord.org.phone}`, margin, 45)
  }
  if (paymentRecord.org.email) {
    pdf.text(`Email: ${paymentRecord.org.email}`, margin, 50)
  }

  // Title
  pdf.setFontSize(18)
  pdf.setTextColor(17, 24, 39)
  pdf.setFont(undefined, 'bold')
  pdf.text('Payment Receipt', margin, 70)

  // Payment Details
  let y = 85
  pdf.setFontSize(10)
  pdf.setTextColor(107, 114, 128)
  pdf.setFont(undefined, 'normal')
  
  pdf.text('Payment Details:', margin, y)
  y += 10
  
  pdf.setFont(undefined, 'bold')
  pdf.setTextColor(17, 24, 39)
  pdf.text('Student:', margin, y)
  pdf.setFont(undefined, 'normal')
  pdf.text(`${paymentRecord.student.firstName} ${paymentRecord.student.lastName}`, margin + 30, y)
  y += 8

  pdf.setFont(undefined, 'bold')
  pdf.text('Class:', margin, y)
  pdf.setFont(undefined, 'normal')
  pdf.text(paymentRecord.class.name, margin + 30, y)
  y += 8

  pdf.setFont(undefined, 'bold')
  pdf.text('Month:', margin, y)
  pdf.setFont(undefined, 'normal')
  pdf.text(paymentRecord.month, margin + 30, y)
  y += 8

  pdf.setFont(undefined, 'bold')
  pdf.text('Payment Method:', margin, y)
  pdf.setFont(undefined, 'normal')
  const methodLabel = paymentRecord.method === 'CASH' ? 'Cash' 
    : paymentRecord.method === 'BANK_TRANSFER' ? 'Bank Transfer' 
    : paymentRecord.method === 'STRIPE' ? 'Card Payment' 
    : paymentRecord.method || 'Not specified'
  pdf.text(methodLabel, margin + 40, y)
  y += 8

  if (paymentRecord.reference) {
    pdf.setFont(undefined, 'bold')
    pdf.text('Reference:', margin, y)
    pdf.setFont(undefined, 'normal')
    pdf.text(paymentRecord.reference, margin + 30, y)
    y += 8
  }

  if (paymentRecord.paidAt) {
    pdf.setFont(undefined, 'bold')
    pdf.text('Date Paid:', margin, y)
    pdf.setFont(undefined, 'normal')
    pdf.text(new Date(paymentRecord.paidAt).toLocaleDateString('en-GB', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    }), margin + 30, y)
    y += 8
  }

  // Amount
  y += 5
  pdf.setFontSize(16)
  pdf.setFont(undefined, 'bold')
  pdf.setTextColor(17, 24, 39)
  pdf.text('Amount Paid:', margin, y)
  
  const amount = (paymentRecord.amountP / 100).toFixed(2)
  pdf.setFontSize(20)
  pdf.setTextColor(34, 197, 94) // green-500
  pdf.text(`£${amount}`, pageWidth - margin - 30, y, { align: 'right' })

  // Notes
  if (paymentRecord.notes) {
    y += 15
    pdf.setFontSize(10)
    pdf.setTextColor(107, 114, 128)
    pdf.setFont(undefined, 'normal')
    pdf.text('Notes:', margin, y)
    y += 8
    pdf.setFontSize(9)
    pdf.text(paymentRecord.notes, margin, y, { maxWidth: pageWidth - (margin * 2) })
  }

  // Footer
  const footerY = pdf.internal.pageSize.getHeight() - 20
  pdf.setFontSize(8)
  pdf.setTextColor(156, 163, 175) // gray-400
  pdf.text('Generated by Madrasah OS', margin, footerY)
  pdf.text(`Payment Record ID: ${paymentRecord.id.slice(-8)}`, pageWidth - margin, footerY, { align: 'right' })

  // Thank you message
  y = footerY - 15
  pdf.setFontSize(12)
  pdf.setTextColor(17, 24, 39)
  pdf.setFont(undefined, 'bold')
  pdf.text('Jazakallahu Khairan', pageWidth / 2, y, { align: 'center' })
  pdf.setFontSize(10)
  pdf.setFont(undefined, 'normal')
  pdf.setTextColor(107, 114, 128)
  pdf.text('Thank you for your payment', pageWidth / 2, y + 8, { align: 'center' })

  return Buffer.from(pdf.output('arraybuffer'))
}

