import jsPDF from 'jspdf'
import { prisma } from './prisma'
import { uploadFile, BUCKETS } from './storage'

export async function generateInvoicePDF(invoiceId: string): Promise<string> {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      student: true,
      org: true,
      payments: {
        where: { status: 'SUCCEEDED' }
      }
    }
  })
  
  if (!invoice) {
    throw new Error('Invoice not found')
  }
  
  const pdf = new jsPDF()
  
  // Header
  pdf.setFontSize(20)
  pdf.text(invoice.org.name, 20, 30)
  
  pdf.setFontSize(12)
  pdf.text('Invoice', 20, 45)
  pdf.text(`#${invoice.id.slice(-8)}`, 20, 55)
  pdf.text(`Date: ${invoice.createdAt.toLocaleDateString()}`, 20, 65)
  pdf.text(`Due: ${invoice.dueDate.toLocaleDateString()}`, 20, 75)
  
  // Student info
  pdf.text('Bill To:', 20, 95)
  pdf.text(`${invoice.student.firstName} ${invoice.student.lastName}`, 20, 105)
  
  // Amount
  const amount = (invoice.amountP / 100).toFixed(2)
  pdf.text(`Amount: £${amount}`, 20, 125)
  
  // Status
  const status = invoice.status
  pdf.text(`Status: ${status}`, 20, 135)
  
  // Payment history
  if (invoice.payments.length > 0) {
    pdf.text('Payment History:', 20, 155)
    let y = 165
    for (const payment of invoice.payments) {
      const paymentAmount = (payment.amountP / 100).toFixed(2)
      pdf.text(`- ${payment.method}: £${paymentAmount} (${payment.status})`, 20, y)
      y += 10
    }
  }
  
  // Footer
  pdf.setFontSize(8)
  pdf.text('Generated by Madrasah OS', 20, 280)
  
  const pdfBuffer = Buffer.from(pdf.output('arraybuffer'))
  const fileName = `invoice-${invoice.id}-${Date.now()}.pdf`
  const path = `invoices/${invoice.orgId}/${fileName}`
  
  await uploadFile(BUCKETS.INVOICES, path, pdfBuffer, 'application/pdf')
  
  return path
}
